### ISSUE TITLE
React.__spread vs react/lib/Object.assign in Navigate.js

### ISSUE THREAD

**Issue by Kingdutch** [zertosh/ssr-demo-kit#4]
What's the reason for using `React.__spread` in Navigate.js? In the React sourcecode this is simply assigned as an alias for react/lib/Object.assign with the notion to not use it for anything else.

`react/lib/Object.assign` is already being used in AppDispatcher so it wouldn't be new if it was used here. 

While typing this issue the notion of Navigate.js being a compiled .jsx template creeps up on me. If that's the case then my question is answered, this issue can be closed and it serves as a fine example of how jsx and js components can be used alongside one another with this architecture.

**Comment by zertosh** [comment]
Yeah it was a compile + copy/paste. I just merged https://github.com/zertosh/ssr-demo-kit/pull/6 with some updates, including using `React.DOM` and `assign` instead of `React.createElement` and `React.__spread`.

**Comment by Kingdutch** [comment]
:+1:
